version: '3.8'

services:
  app:
    build: .
    command: bash start.sh
    ports:
      - "3000:3000"
    volumes:
      - .:/jobs-api
    environment:
      DATABASE_URL: postgres://jobs_api:jobs_api@db/onebitjobs_development
      NODE_ENV: development
    depends_on:
      - db
    networks:
      - api-sequelize
  db:
    image: postgres:14.2
    environment:
      POSTGRES_DB: onebitjobs_development
      POSTGRES_USER: jobs_api
      POSTGRES_PASSWORD: jobs_api
    ports:
      - "5432:5432"
    networks:
      - api-sequelize

networks:
  api-sequelize:
    driver: bridge
volumes:
  db: